<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE SERVICE_MAPPINGS [
	<!ELEMENT SERVICE_MAPPINGS (SERVICE*)>
	<!ELEMENT SERVICE (NAME,BEAN_HOME_INTF)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT BEAN_HOME_INTF (#PCDATA)>
]>

<SERVICE_MAPPINGS>
	<SERVICE>
		<NAME>serv_create_1b5d041851ec6be5_f56b46433bc43525(LBankCustomer.Customer)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_get_c150b107d88ea80_f4ca67ea6ee22f93(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_modify_80fea8b2e198f821_8a41c9812eea9ee6(LBankCustomer.Customer)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_delete_78a659e1cad67512_563dafdb773a78ad(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_getAll_e5749de34cedb8cb_d4605612fbc710b9(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_getById_7aacbdd6094d4b25_e8033709eae019f3(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>serv_createNdModify_b0aa0ea46bbc7cec_3fb05df48dce0680(LBankCustomer.Customer)</NAME>
		<BEAN_HOME_INTF>BankCustomerBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
</SERVICE_MAPPINGS>
