<?xml version='1.0' encoding='utf-8'?>

<!DOCTYPE SERVICE_MAPPINGS [
	<!ELEMENT SERVICE_MAPPINGS (SERVICE*)>
	<!ELEMENT SERVICE (NAME,BEAN_HOME_INTF)>
	<!ELEMENT NAME (#PCDATA)>
	<!ELEMENT BEAN_HOME_INTF (#PCDATA)>
]>

<SERVICE_MAPPINGS>
	<SERVICE>
		<NAME>svc_craeteForScalarAllOpt_cf867ead8e8413aa_8060ba7667c4fbb5(LRegressionComponent.ScalarClsWithAllDataTypOpt)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchScalarAllOpt_2fc1a0ccbbf63f01_dbf3ee72da972b7e(Ljava.lang.String)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyScalarAllOpt_c01b6e903eb312_4f8da64feeb11458(LRegressionComponent.ScalarClsWithAllDataTypOpt)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_getScalarAllOpt_16c0b61471f2d01d_ebda25294ac2296(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteScalarAllOpt_3844e387f115b7c1_5c2aba54fd413d00(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_createScalarAllMndtry_316cd8c1f1e8fea7_bef04667e3286254(LRegressionComponent.ScalarClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchScalarAllMndtry_879e8be1ce4e9c66_62d7b54d8939589d(LRegressionComponent.ScalarClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyScalarAllMndtry_a0ff8a6b53e74619_bf6b1e0da6e3a8f8(LRegressionComponent.ScalarClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteScalarAllMndtry_f1fcc2927b765a92_4f0637939969155b(LRegressionComponent.ScalarClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_createVectorAllOpt_b70f214128c03d85_e9947b4e9d9ceddb(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchVectorAllOpt_8880f8f229b04bf5_bfd49f1a77d88a38(LRegressionComponent.VectorClsAllDataTypOpt)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyVectorAllOpt_1cf631fda12066c5_7386c5ec16ea1332(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteVectorAllOpt_8f12923da8a0d271_4d289c4ee588c302(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_createVectorAllMndtry_7b04d69c79b58614_18f96ab51b64d368(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchVectorAllMndtry_17c603d0f342e93f_e3810ad599f11d80(LRegressionComponent.VectorClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyVectorAllMndtry_447037419d4c8286_85a146a7ca8ea6eb(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteVectorAllMndtry_3112aa7680fc0772_db741f70497881e5(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_getVectorAllMndtry_931a2d35c0e073f8_2c6bbf3048d7b450(LRegressionComponent.VectorClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_getScalarAllMndtry_213ef137a4a0126a_1b4b3da8dbf61ecf(LRegressionComponent.ScalarClsAllDataTypMndtry)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_fetchAllVectorAllMndtry_c17882e2be590275_123b4bbe916c014e()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_fetchAllVectorAllOpt_7e0bd5974a4785fd_bc315641bfbe9d41()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_fetchAllScalarDataTypOpt_7dff44170688fef_7ddc6ef594b59006()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_fetchAllScalarDataTypMndtry_a0deadeb94e31ae7_81002da63dc1088f()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_createClassWithCompositeKey_34c3285f46319145_44118c40f827b0ef(LRegressionComponent.ClsScalarWithCompositeKey)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchClassWithCompositeKey_f744613656baa487_250e6fb089316bea(LRegressionComponent.ClsScalarWithCompositeKey)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyClassWithCompositeKey_ed33d73c03308d2e_9f33cc33e569cbbd(LRegressionComponent.ClsScalarWithCompositeKey)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteClassWithCompositeKey_ef4ff990e3154623_28b8e5bbdb4bdde6(LRegressionComponent.ClsScalarWithCompositeKey)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_CompositeKeyWithClsVectorAllOpr_f9f1e6747d0aa308_1a332f1904c28287(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcCreateAllWidget_baaefb2a5f3c5c26_6ec968eae57b6335(LRegressionComponent.AllWidgetClassDTO)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcModifyAllWidget_a1eae670b63e2e7b_5edf82a378d800fb(LRegressionComponent.AllWidgetClassDTO)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcDeleteAllWidget_5e407727d30a171b_8a59db07e6f1a0e5(Ljava.lang.String)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllWidget_2bcb680ab63ff99a_b02b78da1d3f589f()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcCreateAllWidgetVector_d272f875858a860d_21ed3dbdaa7c879c(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcModifyAllWidgetVector_244bf4141fb15d35_bcd97c23a8c2b707(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcDeleteAllWidgetVector_5430f91b87a864b2_f5a25f617825d2b0(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcSearchByNamellWidgetVector_cef400cbf99d1892_dc51272f2df728a6(Ljava.lang.String)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_FetchSingleScalarAllDataOptDTO_476400ed294a7258_e7635519cf29e3fa(LRegressionComponent.ScalarClsWithAllDataTypOptDTO)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_fetchScalarAllDataOptDTO_4e8cb61226aaadb_faef5e6a0f078d9e(LRegressionComponent.ScalarClsWithAllDataTypOptDTO)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_CompositeFKWithClsVectorAllOpr_4fcb2a3008f48c40_4c48973c11857ce4(Lcom.tcs.mastercraft.mctype.MasterCraftVector)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_createClsWithCompositeFK_9ba146c3b0716f91_406f801cd4f086b8(LRegressionComponent.ClsScalarWithCompositeFK)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_deleteClassWithCompositeFK_e74798a7e7842c9b_900590348c0dbb5c(LRegressionComponent.ClsScalarWithCompositeFK)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_modifyClassWithCompositeFK_69c04e1c105a2bab_157ab1b826241f70(LRegressionComponent.ClsScalarWithCompositeFK)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_searchClassWithCompositeFK_f3fbbc2b21f67fb3_88a8cb038071901(LRegressionComponent.ClsScalarWithCompositeFK)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAlld_IntClsScalarOpt_56425b50b3db916d_8191423827ad2f08()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingled_IntClsScalarOpt_744e42546f069051_9da434d1e36a8f3b(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingleMCFile_96a1d6bfc612d7be_849af6cb591a0ea7(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingledCharClsScalarOpt_9421e5bc0f4123c_c59d14aa03278518(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingleDBooleanClsScalarOpt_755d03f80a0dbc04_20ae1d4f7b6ba4d6(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingleDLongClsScalarOpt_1dbdcabf2bf08f1_8d5fa3d96dd15922(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllDCharClsScalarOpt_f78cf783ded0e657_10ba123fa54abd19()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllDBooleanClsScalarOpt_48e8729083966118_a15850c9c718f5d8()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllDLongClsScalarOpt_2c9b663e48fac35_c1a7fca6475f813c()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllMCFileScalarOpt_c893b978419ce930_4df3462f9efaf6d8()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllDFloatClsScalarOpt_2fb42c4b49150bd4_2ff519a513402ce7()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllDDoubleClsScalarOpt_7e215f61a7464659_b619aa338402dadf()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingleDDoubleClsScalarOpt_dd1d91b8c3571729_e7eb994fa5a0aba0(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchSingleDFloatClsScalarOpt_682cfb7ab41e2e74_9796debe220c129b(LDomains.d_intClass)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svc_FetchAllScalarAllDataOptDTO_5c0274fada2d8f97_b785bbf9ec5b7d6f(LRegressionComponent.ScalarClsWithAllDataTypOptDTO)</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllScalarCompositePKCol_ea2e36678baa7b6e_e545ade4d9123756()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
	<SERVICE>
		<NAME>svcFetchAllVectorCompositePKCol_4699f0602043242a_36320f4b35dbbfa5()</NAME>
		<BEAN_HOME_INTF>RegressionComponentBEAN_LOCAL_INTF</BEAN_HOME_INTF>
	</SERVICE>
</SERVICE_MAPPINGS>
